### ISSUE TITLE
[Specified Style Set Processing] Initial values only applied to regions

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml1#217] opened 2016-10-30 21:26 UTC
The _Specified Style Set Processing_ algorithm only mentions initial values _if the element type of E is the layout element type region, then set P′ to the initial value of property P_.

How do initial values of non-inheritable styling attributes ever apply to elements other than regions?

Shouldn't initial values be applied to all elements and not only region elements?

**Comment by skynavga** [comment] 2016-10-31 19:23
Duplicate of #200.

**Closed as completed by skynavga** 2016-10-31 19:23 UTC
Labels: duplicate
