### ISSUE TITLE
Inconsistent implicit duration of singleton span in sequential container.

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml1#193] opened 2015-11-04 17:39 UTC
The implicit duration of an anonymous span child of a sequential container is explicitly defined to be zero (section 10.4); however, the implicit duration of an explicit singleton (i.e., non-nested) span in the same context 

Here is an example, where I ignore whitespace to aid in viewing. Given a fragment:

```xml
<p timeContainer="seq">
  Foo
  <span>Bar</span>
  Baz
</p>
```

Generating anonymous spans to wrap text nodes:

```xml
<p timeContainer="seq">
  <span xml:id="anon1">Foo</span>
  <span>
    <span xml:id="anon2">Bar</span>
  </span>
  <span xml:id="anon3">Baz</span>
</p>
```

Applying timing semantics as presently defined to resolve implicit duration:

```xml
<p timeContainer="seq" durImplicit="indefinite">
  <span xml:id="anon1" durImplicit="0">Foo</span>
  <span durImplicit="indefinite">
    <span xml:id="anon2" durImplicit="indefinite">Bar</span>
  </span>
  <span xml:id="anon3" durImplicit="0">Baz</span>
</p>
```

Here, anon2 is assigned an indefinite implicit duration because its parent is an explicit span which defaults to 'par' time containment semantics. Since SMIL requires a seq container that contains an indefinite duration child to also be indefinite, then that indefinite propagates up the node tree.

This seems counterintuitive. I propose to resolve by a slight change in 10.4 from the current text:

"if the anonymous span's parent time container is a parallel time container, then the implicit duration is equivalent to the indefinite duration value as defined by [SMIL 2.1]; if the anonymous span's parent time container is a sequential time container, then the implicit duration is equivalent to zero"

to read:

"if the anonymous span's nearest explicit time container ancestor is a sequential time container, then the implicit duration is equivalent to zero; otherwise, it is equivalent to the indefinite duration value as defined by [SMIL 2.1]"

and add the following Note

"Note: An element is an explicit time container if it specifies a timeContainer attribute."

Reworking the above example with the new text, we get:

```xml
<p timeContainer="seq" durImplicit="0">
  <span xml:id="anon1" durImplicit="0">Foo</span>
  <span durImplicit="0">
    <span xml:id="anon2" durImplicit="0">Bar</span>
  </span>
  <span xml:id="anon3" durImplicit="0">Baz</span>
</p>
```

The resolution of this issue also needs applied to TTML2.

(raised by Glenn Adams on 2014-08-26)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/338

**Comment by nigelmegitt** [comment] 2017-01-12 13:57
[Meeting 2017-01-12] @skynavga requests time to check this again. Looks like the durImplicit of 0 might mean the content never appears.

**Comment by nigelmegitt** [comment] 2017-01-13 14:32
[Meeting 2017-01-13] @skynavga to consider not wrapping text content in anonymous spans where they are already wrapped by a non-anonymous span. 

Alternative approach might be to mark this as Wontfix and leave this perhaps surprising behaviour in place as is.

**Comment by palemieux** [comment] 2017-12-14 07:03
> This seems counterintuitive. 

@skynavga and @nigelmegitt What is counterintuitive/surprising in the example above?

**Comment by nigelmegitt** [comment] 2017-12-14 13:45
> What is counterintuitive/surprising in the example above?

@palemieux It is surprising that different timing resolution applies to anonymous spans compared to explicit spans that don't include timing attributes. Do you not think that is strange behaviour?

**Comment by palemieux** [comment] 2017-12-15 21:42
@nigelmegitt I am not sufficiently comfortable with SMIL to understand how the example above will behave. Can you explain how the example above will be rendered over time?

**Comment by nigelmegitt** [comment] 2017-12-15 22:17
@palemieux I think @skynavga has described it pretty well in the main issue comment.

It would render as a `p` containing the text "Bar" until the `p` is forced to end, for example by the application ending or an ancestor element's explicit end time being reached.

In my view the intuitive behaviour would be for it to contain the text "Foo" with the same timing, in other words that the implicit duration of an anonymous span is always indefinite regardless of the parent element's `timeContainer` attribute. @skynavga 's proposal is for the implicit duration of anonymous spans that are children of `seq` timeContainers to be _zero_. The effect of that would be that no content is ever displayed from that `p` element.

An alternative behaviour that some readers might initially expect is that the text "Foo Bar Baz" is all displayed at once, however that would require that all the contents of the `<p>` are placed within a `par` timeContainer, such as a `span`.

[updated to fix copy/paste mangling in description of @skynavga 's proposal, in paragraph 3]

**Comment by nigelmegitt** [comment] 2017-12-15 22:20
Sorry, last comment was mangled, now edited to fix it.

**Comment by palemieux** [comment] 2017-12-16 05:25
@skynavga Do you recall why _if the anonymous span's parent time container is a sequential time container, then the implicit duration is equivalent to zero_? In other words, why shouldn't anonymous spans always have indefinite implicit duration?

**Comment by palemieux** [comment] 2017-12-22 20:59
[needs more time to study]

**Comment by nigelmegitt** [comment] 2017-12-22 22:29
@skynavga is there any practical example where this issue is likely to cause unexpected behaviour? Having looked at it a few times, I think it's an unlikely edge case in which there's no right answer, and I would favour leaving the existing text in 10.4 as is and closing this issue as "works for me". 

One particular motivation for this is that I believe that most document authors would expect a `span` element with no `timeContainer` attribute to behave as a `par` and the proposed change would effectively modify that in some conditions. I would rather leave the initial value of `timeContainer` as `par` and not introduce quasi-inheritance semantics. I think the change is more likely to break existing documents than to correct an unexpected behaviour.

**Comment by palemieux** [comment] 2017-12-22 22:37
By the way, I think there is a typo in the original comment:

_Since SMIL requires a seq container that contains an indefinite duration child to also be indefinite_

should read:

_Since SMIL requires a seq container that contains an indefinite duration child to have an indefinite **implicit duration**_

This is key in my mind since this _implicit duration_ can be overridden by an explicit duration on a parent.

**Comment by palemieux** [comment] 2017-12-28 06:22
I support closing this issue as "works for me", as suggested at https://github.com/w3c/ttml1/issues/193#issuecomment-353684603. This behavior can easily be avoided by wrapping text in spans and specifying explicit durations.

**Comment by skynavga** [comment] 2018-01-04 07:48
Regarding https://github.com/w3c/ttml1/issues/193#issuecomment-352162453, I think it came from the following text in SMIL 2.1, Section 7.3 [1], and Section 10.9.4 [2].

>In SMIL, the implicit duration for any media object that does not have a well-defined duration is set to be zero seconds.

>For simple media elements (i.e., media elements that are not time containers) that reference discrete media, the implicit duration is defined to be 0. This can lead to surprising results, as in this example:
>
```
<seq>
   <img src="img1.jpg" />
   <video src="vid2.mpg" />
   <video src="vid3.mpg" />
</seq>
```

[1] https://www.w3.org/TR/SMIL2/extended-media-object.html#media-Definitions
[2] https://www.w3.org/TR/SMIL2/smil-timing.html#Timing-Ex:0DurDiscreteMedia

I seem to recall at one point, we had the same semantic apply to text (anonymous spans) for par time containers as well, but decided that wouldn't make sense, so changed to indefinite (for par), but did not do the same for seq. A review of old minutes prior to November 2004 might come up with something more concrete.

**Comment by skynavga** [comment] 2018-01-04 07:50
I can accept a works for me, but would prefer a note at the end of 10.4 that notes the possibility of a surprising result in this context.

**Comment by nigelmegitt** [comment] 2018-01-04 10:01
> .... a note at the end of 10.4 that notes the possibility of a surprising result in this context.

Seems reasonable - what would the note text be @skynavga ?

**Comment by skynavga** [comment] 2018-01-04 21:07
I was just reviewing the PR (#318), and the thought struck me (again - I have considered it in the past) that we should map a span with one or more anonymous span children to the parent span, i.e., de-encapsulate the nested anonymous spans. If that were done, then the resulting (non-anonymous) span would have an implicit duration of 0, so we would not have the exceptional situation discussed above.

**Comment by nigelmegitt** [comment] 2018-01-05 13:41
@skynavga I don't follow: In the example provided in this issue the anonymous spans that are children of the p are not nested in a parent span. Could you provide an example showing what the difference would be?

**Comment by palemieux** [comment] 2018-01-16 19:31
See _Inconsistent implicit duration of singleton span in sequential container. ttml1#193_ at https://www.w3.org/2018/01/09-tt-minutes.html

**Closed as completed** 2018-01-21 05:43 UTC
Labels: pr open
