### ISSUE TITLE
Use of attributes in TTML namespace but NOT defined in TTML1 

### ISSUE THREAD

**Issue by andreastai** [w3c/ttml1#251] opened 2017-07-22 09:34 UTC
Content models of TTML elements are defined as Element Information Items and represented in XML. One example is the content model of the `style` element:

```
<style
  style = IDREFS
  xml:id = ID
  xml:lang = string
  xml:space = (default|preserve)
  {any attribute in TT Style namespace}
  {any attribute not in default or any TT namespace}>
 Content: EMPTY
</style>
```
The content models give a "general allowance" to use attributes of a specific namespace. In the above example, any attribute that is in the TT Style namespace ("http://www.w3.org/ns/ttml#styling") can be used. 

My question is, if this is restricted to just the attributes of "http://www.w3.org/ns/ttml#styling" that are defined in TTML1 (see [Section 5.3.1 of TTML1, Table 5](https://www.w3.org/TR/ttaf1-dfxp/#core-vocabulary-overview)), if also attributes are allowed that have been defined for the TTML Style namespace in a later publication of W3C (e.g. TTML2) or if from the element type defintion it doesn't matter where attribute is defined, it just needs to be in the TTML Style namespace.

**Comment by andreastai** [comment] 2017-07-25 18:38
My interpretation is that by the syntax definition all attributes are allowed to be added if they are in one of the namespaces in question, e.g. the following 

`  {any attribute in TT Style namespace}`

would make the following TTML legal (prefix `tts` is bound as defined in TTML1):

```xml
<style tts:foo="bar"... />
```
Although the namespaces defined TTML are in the authority of the W3C, a processor needs to accept a document with arbitrary attributes in the TTML style namespace. It is not possible to know which attributes in that namespace will be specified in the future (by whatever W3C standard group).

**Comment by skynavga** [comment] 2017-07-25 20:02
On Tue, Jul 25, 2017 at 12:38 PM, Andreas Tai <notifications@github.com>
wrote:

> My interpretation is that by the syntax definition all attributes are
> allowed to be added if they are in one of the namespaces in question, e.g.
> the following
>
> {any attribute in TT Style namespace}
>
> would make the following TTML legal (prefix tts is bound as defined in
> TTML1):
>
> <style tts:foo="bar"... />
>
> Although the namespaces defined TTML are in the authority of the W3C, a
> processor needs to accept a document with arbitrary attributes in the TTML
> style namespace. It is not possible to know which attributes in that
> namespace will be specified in the future (by whatever W3C standard group).
>
I basically agree with this interpretation. However, the appearance of an
unknown attribute in a (known at a given time) namespace should not be a
cause to reject the document, that is, unless the purpose of the processor
is to verify strict adherence to whichever version of TTML is being used
for that processing.

Note also the following language that appears at the end of [1] in the
original publication of TTML1:

All TTML Namespaces are *mutable*
> <http://www.w3.org/2001/tag/doc/namespaceState#namespacedef> [NSState]
> <https://www.w3.org/TR/2010/REC-ttaf1-dfxp-20101118/#nsstate>; all
> undefined names in these namespaces are reserved for future standardization
> by the W3C.


[1]
https://www.w3.org/TR/2010/REC-ttaf1-dfxp-20101118/#vocabulary-namespaces

Also, I note the existence of Issue #196 [2], which would seem to make this
new issue a duplicate. If you agree, then you can close this one and mark
as a duplicate.

[2] https://github.com/w3c/ttml1/issues/196

**Comment by mikedo** [comment] 2017-07-26 21:31
I'm not sure I agree with this implied broader interpretation.  Conformant TTML1 documents have the up to the defined TTML1 (e.g. tts:) namespace attributes and no more.

That said, well-implemented TTML1 decoders should be tolerant (and gracefully ignore) unknown TTML1 (e.g. tts:) namespace attributes in TTML namespaces.

**Comment by skynavga** [comment] 2017-07-26 21:42
On Wed, Jul 26, 2017 at 3:31 PM, Michael A Dolan <notifications@github.com>
wrote:

> I'm not sure I agree with this implied broader interpretation. Conformant
> TTML1 documents have the up to the defined TTML1 (e.g. tts:) namespace
> attributes and no more.
>
I agree that an purported TTML1 document that contains extensions in TTML
namespaces not known to TTML1 would not be strictly conformant. However, I
think we can also recognize lax conformance as well. In a validation
processor, I would expect at least a warning and perhaps an error to be
reported (as a default) when encountering such extensions.


> That said, well-implemented TTML1 decoders should be tolerant (and
> gracefully ignore) unknown TTML1 (e.g. tts:) namespace attributes in TTML
> namespaces.
>
Yes. And we baked that into the spec when we said, under Generic Processor
Conformance, the following:

The processor does not *a priori* reject or abort the processing of a
conformant *Document Instance* unless the processor does not support some
required (mandatory) feature specified or implied by a TTML profile
declared to apply to the *Document Instance*.


I view this as applying to documents claiming either strict conformance or
lax conformance. Note, however, that we don't have any way for an author to
signal they view one or the other of these models of conformance to apply.

**Comment by mikedo** [comment] 2017-07-26 21:52
OK, glad we agree on the original intent.  Then, what's the issue and what should change in TTML1?  I'm not seeing it.  Maybe a clarification somewhere? But I do not agree with the original premise in this issue about an instance document being therefore "legal". We should stick to instance document conformance and decoder conformance and not introduce "legal", "strict", and "lax" at this stage.

**Comment by skynavga** [comment] 2017-07-26 22:00
Take a look at https://github.com/w3c/ttml1/issues/196, which better
expresses the issue IMO. [I'm waiting for Andreas input before closing this
current issue #251 as a duplicate of #196.]

**Comment by palemieux** [comment] 2017-07-26 23:43
@mikedo How do you interpret ` {any attribute in TT Style namespace}`?

**Comment by andreastai** [comment] 2017-07-27 14:43
(@mikedo)
> Conformant TTML1 documents have the up to the defined TTML1 (e.g. tts:) namespace attributes and no more.

@mikedo: Can you point me to the spec text that sets this constraint?

@skynavga: This issue should not be closed for now. #196 is not a duplicate of this issue.  It is more related to processors behaviour, while my question is about document conformance against the grammar defined in TTML1.

**Comment by palemieux** [comment] 2017-12-16 19:49
Below is my understanding of the steps involved with evaluation Document Conformance using the `tts:foo="bar"` example above against http://www.w3.org/TR/2013/REC-ttml1-20130924/.

- Document Conformance is defined in Section 3.1 of TTML1
- Criteria 1 and 2 are satisfied
- Criterion 3 is satisfied and the document is associated with the Abstract Document Type defined in Section 4
- Criterion 4 is satisfied since the content specification of `style` allows any attribute in the `TT Style Namespace`, which is mutable. [ed.: it is ambiguous whether _the declared value of each attribute satisfies the type declared by the associated Abstract Document Type_ applies since `tts:foo` is not defined in the specification]

So AFAIK the document is conformant.

[ed.: this conclusion was changed from an earlier version of the comment]

Two important points in my mind:

- how the document will be processed (successfully or not) by a conformant processor is not covered by the discussion above
- the discussion above is only valid for the specific version of the specification mentioned above

Based on discussions with @nigelmegitt , a step (4) to Section 4 to _prune attributes without a type declared by the associated abstract document type_ might be useful.

**Comment by andreastai** [comment] 2017-12-20 16:36
> So AFAIK the document is conformant.

Yes, I agreee. From reading the spec that would also be my conclusion.

> it is ambiguous whether the declared value of each attribute satisfies the type declared by the associated Abstract Document Type applies since tts:foo is not defined in the specificatio

True. It is not clear what the intent is to keep the namespace mutable. I am also not sure if what can be read from the spec, is really what was intended. As @mikedo pointed out he reads it in a way that the use of `tts:foo`would not be conformant.  @skynavga confirmed this.

> how the document will be processed (successfully or not) by a conformant processor is not covered by the discussion above

Not really, that is true. But I think you can infer from the logic that it is implementation dependent as no behaviour is defined for vocabulary outside of TTML1.

> Based on discussions with @nigelmegitt , a step (4) to Section 4 to prune attributes without a type declared by the associated abstract document type might be useful.

Is this consistent? You first declare a document with `tts:foo` conformant and also valid against the Abstract Document Type and then prune it? In this case you should better clarify that 

> {any attribute in TT XX namespace}

means `any in TTML 1 defined attribute in TT XX namespace`

In general the problem is not so much with an attribute like `tts:foo` but with unintended errors like `tts:fontsize`.  A document with `tts:fontsize="100"` would be valid but a document with `tts:fontSize="100"` not. It make errors far more complicated to spot.

**Comment by nigelmegitt** [comment] 2017-12-20 16:54
> >  Based on discussions with @nigelmegitt , a step (4) to Section 4 to prune attributes without a type declared by the associated abstract document type might be useful.

> Is this consistent? You first declare a document with tts:foo conformant and also valid against the Abstract Document Type and then prune it?

No, you prune attributes whose value type conformance cannot be verified (because the type is not defined) _before_ assessing the validity. 

Then you do not need to qualify the `{any attribute in TT XX namespace}` further.

> It make errors far more complicated to spot.

This is one good use for schema validation - it should identify that there is an undefined attribute `tts:fontsize`. 

The alternative (which could also work) is that any attributes whose value type conformance cannot be validated should not be considered valid. Then unrecognised attributes in TTML namespaces would trigger a "not valid" state.

**Comment by skynavga** [comment] 2017-12-22 04:24
As currently written, it is unambiguous in TTML1 that tts:fontsize is not
pruned, but is subject to validation against the Abstract Document Type.
However, what may be ambiguous is that
the specified XML Representation of content elements permit "{any attribute
in TTML style namespace}". This quoted specification phrase can be
interpreted in two ways:

   1. any attribute for which the namespace is resolved to
   http://www.w3.org/ns/ttml#styling, e.g., tts:fontsize (with the usual
   bindings);
   2. only those attributes defined in TTML1 Table 5 for which the
   namespace is resolved to http://www.w3.org/ns/ttml#styling, e.g.,
   tts:fontsize (with the usual bindings).

The first of these suggests the presence of tts:fontsize is conformant, but
the second suggests that it is non-conformant.

For guidance on which of these apply, we can look at the statement about
namespace mutability, viz.

All TTML Namespaces are *mutable*
> <http://www.w3.org/2001/tag/doc/namespaceState#namespacedef> [NSState]
> <https://w3c.github.io/ttml1/index.html#nsstate>; all undefined names in
> these namespaces are reserved for future standardization by the W3C.


This suggests that tts:fontsize is an "undefined name [in the TTML style
namespace]", since it is not defined in Table 5, in which case, the second
interpretation above is more faithful to the text. This interpretation is
further justified by the following text from Section 4 (emphasis added):

TTML Content is an *Abstract Document Type* of a profile of the Timed Text
> Markup Language intended to be used for interchange among distribution
> systems. This document type is defined in terms of the element and
> attribute vocabulary specified in *5 Vocabulary*
> <https://w3c.github.io/ttml1/index.html#vocabulary>.


In the case of TTV, a simple test file that incudes tts:fontsize (see
attached) reports an error:

Timed Text Verifier (TTV) [1.0.0dev] Copyright 2013-16 Skynav, Inc.
[I]:Verifying
{file:///Users/glenn/Library/Mobile%20Documents/com~apple~CloudDocs/work/ttt/ttt-ttv/run/test/test.xml}.
[I]:Verifying resource presence and encoding phase 1...
[I]:Resource encoding sniffed as UTF-8.
[I]:Resource length 215 bytes, decoded as 215 Java characters (char).
[I]:Verifying XML well-formedness phase 2...
[I]:Verifying XSD validity phase 3...
[I]:Verifying semantics phase 4 using 'ttml1' model...
[E]:{file:///Users/glenn/Library/Mobile%20Documents/com~apple~CloudDocs/work/ttt/ttt-ttv/run/test/test.xml}:[3,30]:Unknown
attribute in TT Style namespace '{http://www.w3.org/ns/ttml#styling}fontsize'
not permitted on '{http://www.w3.org/ns/ttml}body'.
[I]:Verification Failed, with 1 error.
[I]:Failed 1 resource.

In the case of TTV, the normative XSD schema published with TTML1 is used
as an sanctioned definition of a TTML Abstract Document Type, and that
schema clearly adopts the second interpretation above.

**Comment by nigelmegitt** [comment] 2017-12-22 11:35
@skynavga you can correct a comment by updating it using the GitHub web interface, if that helps.

> normative XSD schema published with TTML1

Appendix B.1 and B.2 say: 

> This schema does not normatively define the validity of Timed Text Markup Language content as defined by this specification. In particular, the formal validity of TTML Content is defined by 3.1 Content Conformance.

So I don't think the schema helps answer this question, at least normatively.

**Comment by skynavga** [comment] 2017-12-22 19:01
As currently written, it is unambiguous in TTML1 that ``tts:fontsize`` is not pruned, but is subject to validation against the Abstract Document Type. However, what may be ambiguous is that the specified XML Representation of content elements permit ``{any attribute in TTML style namespace}``. This quoted specification phrase can be interpreted in two ways:

1. any attribute for which the namespace is resolved to ``http://www.w3.org/ns/ttml#styling``, e.g., ``tts:fontsize`` (with the usual bindings);
2. only those attributes defined in TTML1 Table 5 for which the namespace is resolved to ``http://www.w3.org/ns/ttml#styling``, only ``tts:fontSize`` but not ``tts:fontsize``.

The first of these suggests the presence of ``tts:fontsize`` is conformant, but the second suggests that it is non-conformant.

For guidance on which of these apply, we can look at the statement about namespace mutability, viz.

> All TTML Namespaces are *mutable* [NSState]; all undefined names in these namespaces are reserved for future standardization by the W3C.


This suggests that ``tts:fontsize`` is an "undefined name [in the TTML style namespace]", since it is not defined in Table 5, in which case, the second interpretation above is more faithful to the text. This interpretation is further justified by the following text from Section 4:

>TTML Content is an *Abstract Document Type* of a profile of the Timed Text Markup Language intended to be used for interchange among distribution systems. This document type is defined in terms of the element and attribute vocabulary specified in 5 Vocabulary.


In the case of TTV, a simple test file that incudes ``tts:fontsize`` (see attached) reports an error:

<pre>
Timed Text Verifier (TTV) [1.0.0dev] Copyright 2013-16 Skynav, Inc.
[I]:Verifying
{file:///Users/glenn/Library/Mobile%20Documents/com~apple~CloudDocs/work/ttt/ttt-ttv/run/test/test.xml}.
[I]:Verifying resource presence and encoding phase 1...
[I]:Resource encoding sniffed as UTF-8.
[I]:Resource length 215 bytes, decoded as 215 Java characters (char).
[I]:Verifying XML well-formedness phase 2...
[I]:Verifying XSD validity phase 3...
[I]:Verifying semantics phase 4 using 'ttml1' model...
[E]:{file:///Users/glenn/Library/Mobile%20Documents/com~apple~CloudDocs/work/ttt/ttt-ttv/run/test/test.xml}:[3,30]:Unknown
attribute in TT Style namespace '{http://www.w3.org/ns/ttml#styling}fontsize'
not permitted on '{http://www.w3.org/ns/ttml}body'.
[I]:Verification Failed, with 1 error.
[I]:Failed 1 resource.
</pre>

In the case of TTV, the normative XSD schema published with TTML1 is used as an sanctioned definition of a TTML Abstract Document Type, and that schema clearly adopts the second interpretation above.

[test.xml.zip](https://github.com/w3c/ttml1/files/1583285/test.xml.zip)

**Comment by skynavga** [comment] 2017-12-22 19:29
@nigelmegitt said

>Appendix B.1 and B.2 say:
>
>>This schema does not normatively define the validity of Timed Text Markup Language content as defined by this specification. In particular, the formal validity of TTML Content is defined by 3.1 Content Conformance.
>
>So I don't think the schema helps answer this question, at least normatively.

Actually, it does help in the sense that it provides evidence of what was intended even if it wasn't formally or clearly documented. For example, if it was intended that undefined names in the style namespace not be considered non-conformant, then we would expect to see a wildcard

```
<xs:anyAttribute namespace="http://www.w3.org/ns/ttml#styling" processContents="lax"/>
```

included for each content element type.

I think the crux of this issue is fixing the ambiguity in ``{any attribute in TTML * namespace}``, which can be done by adding a note at the end of 5.1 that says

>An undefined name in these namespaces means undefined with respect to this version of this specification; furthermore,  such undefined names are not intended to be included in syntax expressions of the form ``{any attribute in TT * namespace}``, where ``*`` refers to ``Metadata``, ``Profile``, and ``Style``.

**Comment by palemieux** [comment] 2017-12-22 19:33
@skynavga According to https://github.com/w3c/ttml1/issues/251#issuecomment-353661397 , a document that conforms to TTML2 and contains `tts:backgroundClip` would not conform to TTML1 Second Edition, right?

**Comment by skynavga** [comment] 2017-12-22 19:57
Correct, provided it is being processed as a TTML1 document. We could decide otherwise (permit use), or recommend against (should not use); however, I am comfortable with an interpretation that makes it an error. But I am willing to be persuaded otherwise.

**Comment by nigelmegitt** [comment] 2017-12-22 20:30
Thinking about this TTML1 vs TTML2 question, I'm concerned about forward compatibility. The idea of potentially modularising the specification in the future does not sit well with the dichotomy presented here either, since in a modular spec the WG would need the freedom to define future modules that are yet to be defined, without invalidating existing processors.

One avenue we have not explored yet for resolving this issue is to define validity with respect to the set of features defined in the applicable content profile. Now TTML1 does not define content profiles, however as a proxy it could be useful to state something along the lines of:

_Any document that contains non-pruned elements or attributes that would not be recognized by the applicable profile is considered to be invalid, i.e. where no feature requiring syntactic support is defined as optional or required; in the absence of any other profile definition the DFXP Full Profile profile applies with respect to this specification._

Is it mixing concepts too far to suggest that the inferred content profile provides a mechanism for fine tuning the abstract document type for a particular set of features?

**Comment by skynavga** [comment] 2017-12-22 20:43
I would be concerned that this is too much of a departure from the existing spec and fielded implementations. I know of at least two deployed implementations of TTML1 presentation engines, one from 2005 and the other from 2014 that would treat the presence of tts:fontsize as an error. However, note that TTML1 does not require a processor to abort processing in the case of non-conformance.

**Comment by nigelmegitt** [comment] 2017-12-22 22:22
@skynavga  I'm not sure what you're referring to by "this" in "this is too much of a departure"?

If you mean the suggestion I make in https://github.com/w3c/ttml1/issues/251#issuecomment-353670013 then I would say that they are behaving exactly as my suggestion would define: there is no optional or mandatory (for processors) feature definition requiring syntactic support for `tts:fontsize` in any of the profiles supported by those implementations, therefore documents containing it would be invalid.

**Comment by andreastai** [comment] 2018-01-02 12:31
I support @skynavga [proposal](https://github.com/w3c/ttml1/issues/251#issuecomment-353657245) to add the following text:

> An undefined name in these namespaces means undefined with respect to this version of this specification; furthermore, such undefined names are not intended to be included in syntax expressions of the form {any attribute in TT * namespace}, where * refers to Metadata, Profile, and Style.

I agree with @palemieux and @skynavga that there are currently ambiguities in the current spec. The specification text therefore needs to be clarified. What should lead us (as in similar issues before) is the question: What was the intent at the time the TTML1 spec was written? I fully agree with @skynavga that you can take the TTML 1 XML Schema as a reference for the intent at time of specification (and beyond). As @skynavga made clear, you would have chosen another wildcard definition if the specification authors wanted to allow vocabulary in TTML 1 namespaces that is not yet in the TTML 1 spec. 

I do not agree with @nigelmegitt proposal to use the profile mechanisms to infer document conformance. Document conformance is defined by the Document Type Definition.

To use absent attribute type definitions as indication for "non-conformance" is an indirect way to solve the issue and does not clarify the problem. It would be therefore no option for me. @skynavga proposed wording brings the missing clarification.

**Comment by nigelmegitt** [comment] 2018-01-02 22:28
@tairt I could probably live with that as a solution for TTML1, however I also am still concerned about forward compatibility. If we put this change into TTML1 Third Edition, then what will the equivalent change be in TTML2? Certainly not the exact same text, because it prevents W3C from adding new vocabulary items in any potential supplementary specifications.

If there's one lesson this whole issue should teach us, it is that we need to be careful about what we permit or prohibit in the future!

By the way: 

> Document conformance is defined by the Document Type Definition.

This may be in the eye of the beholder. If you only use DTD to measure document conformance then it is clear that a lot of documents will qualify as conformant that really are not. This is too weak a measure for me. In fact the only thing that defines document conformance is the specification section titled "Document Conformance".

**Comment by andreastai** [comment] 2018-01-03 13:06
@nigelmegitt 

> I could probably live with that as a solution for TTML1

Good!

>  however I also am still concerned about forward compatibility. If we put this change into TTML1 Third Edition, then what will the equivalent change be in TTML2? Certainly not the exact same text, because it prevents W3C from adding new vocabulary items in any potential supplementary specifications.

An option is to also add text regarding processor conformance. It could be mandated to ingnore unknown attributes (regardless from which namespace) and to not reject documents with unknown attributes. This should go in TTML2.  It could also be discussed if it could be added as clarification in TTML1.

**Comment by nigelmegitt** [comment] 2018-01-04 09:49
> An option is to also add text regarding processor conformance. It could be mandated to ingnore unknown attributes (regardless from which namespace) and to not reject documents with unknown attributes. This should go in TTML2. It could also be discussed if it could be added as clarification in TTML1.

@tairt Both!

**Comment by palemieux** [comment] 2018-01-09 18:31
See #196

**Comment by skynavga** [comment] 2018-01-09 18:34
As pointed out by @palemieux, we have already updated section 4, item 3 to explicitly prune unknown/undefined attributes from existing TT namespaces.

**Comment by andreastai** [comment] 2018-01-09 19:44
This text should be added as the end of section 4.

> Although attributes and elements in TTML namespaces not defined in TTML1 are not members of the collection of elements and attributes defined by the associated Abstract Document Type, they can be included in a TTML document because they will be pruned by step 1 and 3. 
> 
> This means that the following document would represent a Valid Abstract Document Instance although the attribute "tts:foo" and the element "foo" are undefined vocabulary items in the TTML namespaces.

```xml
<tt 
 xmlns="http://www.w3.org/ns/ttml" xmlns:ttp="http://www.w3.org/ns/ttml#parameter"
 xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:ebuttm="urn:ebu:tt:metadata"  ttp:timeBase="media" xml:lang="en"
 ttp:cellResolution="50 30">
	<head>
		<styling>		
			<style xml:id="paragraphStyle" tts:foo="bar" tts:textAlign="center" />
		</styling>
	</head>
	<body>
	    <foo>bar</foo>
		<div>
			<p xml:id="subtitle1" region="bottom" begin="00:00:00.000" end="00:00:05.000" style="paragraphStyle">One line Subtitle.</span>
			</p>
		</div>
	</body>
</tt>
```

**Comment by skynavga** [comment] 2018-01-09 19:49
A more minimal version of the above suggestion in the form of a note may be acceptable to me.

**Comment by nigelmegitt** [comment] 2018-01-09 19:54
@skynavga to propose an informal note at the end of §4.1 to state that the application of schemas for validation is expected nominally to occur post pruning.

**Comment by andreastai** [comment] 2018-01-09 22:21
The following text could be added as note before the existing note of section 4.1: 

> The schemas are designed to be used for validation after the pruning steps 1-3 of section 4 have been applied.

**Closed as completed** 2018-01-23 15:47 UTC
Labels: pr open
